title: Wedgie Knowledge Base
description: The ultimate community resource for definitions, examples, techniques, bios, and more.
theme: just-the-docs

# Navigation (you can expand this as you add pages)
nav_order: 0
has_toc: true
search_enabled: true
