title: Wedgie Knowledge Base
description: Community resource for wedgie definitions, examples, techniques, bios, safety tips, and more.

remote_theme: just-the-docs/just-the-docs@v0.8.1

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-include-cache  # if not there, add it

search_enabled: true
nav_enabled: true  # optional but good for sidebar
color_scheme: auto

theme: just-the-docs
title: Wedgie Knowledge Base
description: The ultimate community resource

layout: home
nav_order: 1
